cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'fpp'
brew 'ack'
brew 'coreutils'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'
brew 'reattach-to-user-namespace'

cask '1password'
cask 'atom'
cask 'firefox'
cask 'google-chrome'
cask 'handbrake'
cask 'slack'
